// ABOUTME: Asserts both wrangler configs carry the Phase-7 deploy-prep shape.
// ABOUTME: AI binding on both workers, per-env blocks, SSRF flag, no nodejs_compat on research, no cron yet.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(__dirname, "../..");

// Structural shape of the slices of a wrangler config this suite asserts on. Optional
// throughout because the same reader parses both worker configs and every env block, and
// the assertions are what pin which fields must actually be present.
interface QueueProducer {
  binding: string;
  queue: string;
}
interface QueueConsumer {
  queue: string;
  max_batch_size?: number;
  max_retries?: number;
  dead_letter_queue?: string;
}
interface QueuesBlock {
  producers?: QueueProducer[];
  consumers?: QueueConsumer[];
}
interface D1Binding {
  binding: string;
  database_name?: string;
  database_id?: string;
}
interface ServiceBinding {
  binding: string;
  service: string;
}
interface EnvBlock {
  name?: string;
  services?: ServiceBinding[];
  d1_databases?: D1Binding[];
  queues?: QueuesBlock;
  triggers?: { crons?: string[] };
}
interface WranglerConfig {
  ai?: { binding: string; remote?: boolean };
  compatibility_flags?: string[];
  triggers?: { crons?: string[] };
  env?: { dev?: EnvBlock; production?: EnvBlock };
}

// Minimal JSONC reader: drop block + line comments, then JSON.parse.
// Worker configs are author-controlled (not untrusted), so a simple strip is safe here.
// The line-comment strip preserves a leading non-comment char so it never eats a "://" in a URL.
function readJsonc(relPath: string): WranglerConfig {
  const raw = readFileSync(resolve(root, relPath), "utf8");
  const noBlock = raw.replace(/\/\*[\s\S]*?\*\//g, "");
  const noLine = noBlock.replace(/(^|[^:"])\/\/.*$/gm, "$1");
  return JSON.parse(noLine) as WranglerConfig;
}

describe("wrangler config — AI binding (Task 7.1)", () => {
  // The shipped bindings carry `remote: true` (Phase 1 deviation D4 — AI bindings have no
  // local emulation, so remote:true silences the Miniflare stderr warning). Assert the real
  // shipped shape, not an idealized one (testing-pitfalls §6: test the config that ships).
  it("root app worker declares the AI binding", () => {
    const cfg = readJsonc("wrangler.jsonc");
    expect(cfg.ai?.binding).toBe("AI");
  });

  it("research worker declares the AI binding", () => {
    const cfg = readJsonc("workers/research/wrangler.jsonc");
    expect(cfg.ai?.binding).toBe("AI");
  });

  it("cloudflare-env.d.ts exposes AI (app worker, regenerated by cf-typegen)", () => {
    const dts = readFileSync(resolve(root, "cloudflare-env.d.ts"), "utf8");
    expect(dts).toMatch(/\bAI\s*:\s*Ai\b/);
  });

  it("research worker env type declares AI by hand (cf-typegen does not see it)", () => {
    const src = readFileSync(resolve(root, "workers/research/index.ts"), "utf8");
    expect(src).toMatch(/interface ResearchWorkerEnv[\s\S]*?\bAI\s*:\s*Ai\b/);
  });
});

describe("wrangler config — per-env blocks (Task 7.2)", () => {
  // Narrow an optional env block to a present one. Throwing here IS the presence assertion:
  // a missing env block fails the test with a clear message instead of a downcast `undefined`.
  function envOf(cfg: WranglerConfig, which: "dev" | "production"): EnvBlock {
    const block = cfg.env?.[which];
    if (!block) throw new Error(`expected env.${which} block to be present`);
    return block;
  }

  it("app worker has dev + production env blocks with distinct worker names", () => {
    const cfg = readJsonc("wrangler.jsonc");
    expect(envOf(cfg, "dev").name).toBe("wiki-as-of-now-dev");
    expect(envOf(cfg, "production").name).toBe("wiki-as-of-now");
  });

  it("app worker per-env self-reference service matches the per-env worker name", () => {
    const cfg = readJsonc("wrangler.jsonc");
    const devSvc = envOf(cfg, "dev").services?.find((s) => s.binding === "WORKER_SELF_REFERENCE");
    const prodSvc = envOf(cfg, "production").services?.find((s) => s.binding === "WORKER_SELF_REFERENCE");
    expect(devSvc?.service).toBe("wiki-as-of-now-dev");
    expect(prodSvc?.service).toBe("wiki-as-of-now");
  });

  it("app worker per-env queue producer points at the per-env queue", () => {
    const cfg = readJsonc("wrangler.jsonc");
    expect(envOf(cfg, "dev").queues?.producers?.[0].queue).toBe("research-dev");
    expect(envOf(cfg, "production").queues?.producers?.[0].queue).toBe("research");
  });

  it("research worker dev queues are -dev suffixed; prod queues are bare", () => {
    const cfg = readJsonc("workers/research/wrangler.jsonc");
    const dev = envOf(cfg, "dev").queues;
    const prod = envOf(cfg, "production").queues;
    expect(dev?.producers?.[0].queue).toBe("research-dev");
    expect(dev?.consumers?.[0].queue).toBe("research-dev");
    expect(dev?.consumers?.[0].dead_letter_queue).toBe("research-dlq-dev");
    expect(prod?.producers?.[0].queue).toBe("research");
    expect(prod?.consumers?.[0].queue).toBe("research");
    expect(prod?.consumers?.[0].dead_letter_queue).toBe("research-dlq");
  });

  it("research worker keeps max_batch_size 1 in both envs (G14 sequential drain)", () => {
    const cfg = readJsonc("workers/research/wrangler.jsonc");
    expect(envOf(cfg, "dev").queues?.consumers?.[0].max_batch_size).toBe(1);
    expect(envOf(cfg, "production").queues?.consumers?.[0].max_batch_size).toBe(1);
  });

  it("research worker per-env names are distinct", () => {
    const cfg = readJsonc("workers/research/wrangler.jsonc");
    expect(envOf(cfg, "dev").name).toBe("wiki-as-of-now-research-dev");
    expect(envOf(cfg, "production").name).toBe("wiki-as-of-now-research");
  });

  it("both workers point at the same per-env D1 database_name (shared DB per env, CC-10)", () => {
    const app = readJsonc("wrangler.jsonc");
    const research = readJsonc("workers/research/wrangler.jsonc");
    expect(envOf(app, "dev").d1_databases?.[0].database_name).toBe("wiki-as-of-now-dev");
    expect(envOf(research, "dev").d1_databases?.[0].database_name).toBe("wiki-as-of-now-dev");
    expect(envOf(app, "production").d1_databases?.[0].database_name).toBe("wiki-as-of-now");
    expect(envOf(research, "production").d1_databases?.[0].database_name).toBe("wiki-as-of-now");
  });

  it("D1 ids stay placeholders (no real ids committed; provisioning fills them)", () => {
    const app = readJsonc("wrangler.jsonc");
    const research = readJsonc("workers/research/wrangler.jsonc");
    expect(envOf(app, "dev").d1_databases?.[0].database_id).toBe("REPLACE_WITH_DEV_D1_ID");
    expect(envOf(app, "production").d1_databases?.[0].database_id).toBe("REPLACE_WITH_PROD_D1_ID");
    expect(envOf(research, "dev").d1_databases?.[0].database_id).toBe("REPLACE_WITH_DEV_D1_ID");
    expect(envOf(research, "production").d1_databases?.[0].database_id).toBe("REPLACE_WITH_PROD_D1_ID");
  });

  it("the DLQ is never declared as a producer/consumer binding (inferred from dead_letter_queue only)", () => {
    const cfg = readJsonc("workers/research/wrangler.jsonc");
    const dev = envOf(cfg, "dev").queues;
    const prod = envOf(cfg, "production").queues;
    const allQueueRefs = [
      ...(dev?.producers ?? []).map((p) => p.queue),
      ...(dev?.consumers ?? []).map((c) => c.queue),
      ...(prod?.producers ?? []).map((p) => p.queue),
      ...(prod?.consumers ?? []).map((c) => c.queue),
    ];
    expect(allQueueRefs).not.toContain("research-dlq");
    expect(allQueueRefs).not.toContain("research-dlq-dev");
  });

  it("both workers keep global_fetch_strictly_public and research keeps no nodejs_compat", () => {
    const app = readJsonc("wrangler.jsonc");
    const research = readJsonc("workers/research/wrangler.jsonc");
    expect(app.compatibility_flags).toContain("global_fetch_strictly_public");
    expect(research.compatibility_flags).toContain("global_fetch_strictly_public");
    expect(research.compatibility_flags).not.toContain("nodejs_compat");
  });

  it("no cron triggers are declared in either config yet (cron is the last go-live step)", () => {
    const app = readJsonc("wrangler.jsonc");
    const research = readJsonc("workers/research/wrangler.jsonc");
    expect(app.triggers?.crons ?? []).toEqual([]);
    expect(research.triggers?.crons ?? []).toEqual([]);
    expect(app.env?.dev?.triggers?.crons ?? []).toEqual([]);
    expect(app.env?.production?.triggers?.crons ?? []).toEqual([]);
    expect(research.env?.dev?.triggers?.crons ?? []).toEqual([]);
    expect(research.env?.production?.triggers?.crons ?? []).toEqual([]);
  });
});

describe("provision.md stays in sync with configs (Task 7.4)", () => {
  const provision = readFileSync(resolve(root, "scripts/provision.md"), "utf8");
  it("documents creating every queue the research config references", () => {
    for (const q of ["research", "research-dlq", "research-dev", "research-dlq-dev"]) {
      expect(provision).toContain(`bunx wrangler queues create ${q}`);
    }
  });
  it("documents creating both D1 databases by name", () => {
    expect(provision).toContain("bunx wrangler d1 create wiki-as-of-now-dev");
    expect(provision).toContain("bunx wrangler d1 create wiki-as-of-now");
  });
  it("documents remote migration apply per env", () => {
    expect(provision).toMatch(/bunx wrangler d1 migrations apply .*--remote/);
  });
  it("documents put-ing every Phase-5 secret by name", () => {
    for (const s of [
      "SESSION_SECRET",
      "ADMIN_SECRET",
      "GOOGLE_CLIENT_ID",
      "GOOGLE_CLIENT_SECRET",
      "RESEARCH_KILL_SWITCH",
      "BRAVE_API_KEY",
    ]) {
      expect(provision).toContain(`bunx wrangler secret put ${s}`);
    }
  });
  it("uses bunx, never npx", () => {
    expect(provision).not.toMatch(/\bnpx wrangler\b/);
  });
});

describe("CI gates the bundle build + dry-run (Task 7.5)", () => {
  const ci = readFileSync(resolve(root, ".github/workflows/ci.yml"), "utf8");
  it("CI builds the OpenNext bundle", () => {
    expect(ci).toMatch(/opennextjs-cloudflare build/);
  });
  it("CI dry-run-deploys both workers (no real deploy)", () => {
    // CI uses `pnpm exec wrangler` (the pnpm toolchain); human runbooks use `bunx wrangler`.
    expect(ci).toMatch(/(?:bunx|pnpm exec) wrangler deploy --dry-run/);
    expect(ci).toMatch(/(?:bunx|pnpm exec) wrangler deploy --dry-run.*-c workers\/research\/wrangler\.jsonc/);
  });
  it("CI runs the research bundle-cleanliness backstop", () => {
    expect(ci).toMatch(/check:bundle|check-research-bundle-clean/);
  });
  it("CI never does a real (non-dry-run) deploy", () => {
    // Every wrangler deploy line in ci.yml MUST carry --dry-run (the PR job never touches the live account).
    const deployLines = ci.split("\n").filter((l) => /wrangler deploy/.test(l));
    expect(deployLines.length).toBeGreaterThan(0);
    for (const line of deployLines) expect(line).toMatch(/--dry-run/);
  });
});
