// ABOUTME: Asserts both wrangler configs carry the Phase-7 deploy-prep shape.
// ABOUTME: AI binding on both workers, per-env blocks, SSRF flag, no nodejs_compat on research, no cron yet.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(__dirname, "../..");

// Minimal JSONC reader: drop block + line comments, then JSON.parse.
// Worker configs are author-controlled (not untrusted), so a simple strip is safe here.
// The line-comment strip preserves a leading non-comment char so it never eats a "://" in a URL.
function readJsonc(relPath: string): any {
  const raw = readFileSync(resolve(root, relPath), "utf8");
  const noBlock = raw.replace(/\/\*[\s\S]*?\*\//g, "");
  const noLine = noBlock.replace(/(^|[^:"])\/\/.*$/gm, "$1");
  return JSON.parse(noLine);
}

describe("wrangler config — AI binding (Task 7.1)", () => {
  // The shipped bindings carry `remote: true` (Phase 1 deviation D4 — AI bindings have no
  // local emulation, so remote:true silences the Miniflare stderr warning). Assert the real
  // shipped shape, not an idealized one (testing-pitfalls §6: test the config that ships).
  it("root app worker declares the AI binding", () => {
    const cfg = readJsonc("wrangler.jsonc");
    expect(cfg.ai.binding).toBe("AI");
  });

  it("research worker declares the AI binding", () => {
    const cfg = readJsonc("workers/research/wrangler.jsonc");
    expect(cfg.ai.binding).toBe("AI");
  });

  it("cloudflare-env.d.ts exposes AI (app worker, regenerated by cf-typegen)", () => {
    const dts = readFileSync(resolve(root, "cloudflare-env.d.ts"), "utf8");
    expect(dts).toMatch(/\bAI\s*:\s*Ai\b/);
  });

  it("research worker env type declares AI by hand (cf-typegen does not see it)", () => {
    const src = readFileSync(resolve(root, "workers/research/index.ts"), "utf8");
    expect(src).toMatch(/interface ResearchWorkerEnv[\s\S]*?\bAI\s*:\s*Ai\b/);
  });
});
